### ISSUE TITLE
crashing when retrieving feed today

### ISSUE THREAD

**Issue by sejo21** [cathaypacific8747/fr24#23]
Seems to have stopped working today

(grpc) [root@smj-centos-6 grpc]# fr24 feed
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /root/e1radar/grpc/lib64/python3.11/site-packages/fr24/cli.py:98 in feed                         │
│                                                                                                  │
│    95 │   │   │   lf.data.save_parquet()                                                         │
│    96 │   │   │   rich.print(get_success_message(lf))                                            │
│    97 │                                                                                          │
│ ❱  98 │   asyncio.run(feed_())                                                                   │
│    99                                                                                            │
│   100                                                                                            │
│   101 if __name__ == "__main__":                                                                 │
│                                                                                                  │
│ ╭─────────────────────────── locals ───────────────────────────╮                                 │
│ │     feed_ = <function feed.<locals>.feed_ at 0x7fddb33f3b00> │                                 │
│ │      time = None                                             │                                 │
│ │ timestamp = None                                             │                                 │
│ ╰──────────────────────────────────────────────────────────────╯                                 │
│                                                                                                  │
│ /usr/lib64/python3.11/asyncio/runners.py:190 in run                                              │
│                                                                                                  │
│   187 │   │   │   "asyncio.run() cannot be called from a running event loop")                    │
│   188 │                                                                                          │
│   189 │   with Runner(debug=debug) as runner:                                                    │
│ ❱ 190 │   │   return runner.run(main)                                                            │
│   191                                                                                            │
│   192                                                                                            │
│   193 def _cancel_all_tasks(loop):                                                               │
│                                                                                                  │
│ ╭───────────────────────────── locals ──────────────────────────────╮                            │
│ │  debug = None                                                     │                            │
│ │   main = <coroutine object feed.<locals>.feed_ at 0x7fddb3400c70> │                            │
│ │ runner = <asyncio.runners.Runner object at 0x7fddb321fd50>        │                            │
│ ╰───────────────────────────────────────────────────────────────────╯                            │
│                                                                                                  │
│ /usr/lib64/python3.11/asyncio/runners.py:118 in run                                              │
│                                                                                                  │
│   115 │   │                                                                                      │
│   116 │   │   self._interrupt_count = 0                                                          │
│   117 │   │   try:                                                                               │
│ ❱ 118 │   │   │   return self._loop.run_until_complete(task)                                     │
│   119 │   │   except exceptions.CancelledError:                                                  │
│   120 │   │   │   if self._interrupt_count > 0:                                                  │
│   121 │   │   │   │   uncancel = getattr(task, "uncancel", None)                                 │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │        context = <_contextvars.Context object at 0x7fddb3a2dec0>                             │ │
│ │           coro = <coroutine object feed.<locals>.feed_ at 0x7fddb3400c70>                    │ │
│ │           self = <asyncio.runners.Runner object at 0x7fddb321fd50>                           │ │
│ │ sigint_handler = functools.partial(<bound method Runner._on_sigint of                        │ │
│ │                  <asyncio.runners.Runner object at 0x7fddb321fd50>>, main_task=<Task         │ │
│ │                  finished name='Task-1' coro=<feed.<locals>.feed_() done, defined at         │ │
│ │                  /root/e1radar/grpc/lib64/python3.11/site-packages/fr24/cli.py:91>           │ │
│ │                  exception=AssertionError()>)                                                │ │
│ │           task = <Task finished name='Task-1' coro=<feed.<locals>.feed_() done, defined at   │ │
│ │                  /root/e1radar/grpc/lib64/python3.11/site-packages/fr24/cli.py:91>           │ │
│ │                  exception=AssertionError()>                                                 │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /usr/lib64/python3.11/asyncio/base_events.py:653 in run_until_complete                           │
│                                                                                                  │
│    650 │   │   if not future.done():                                                             │
│    651 │   │   │   raise RuntimeError('Event loop stopped before Future completed.')             │
│    652 │   │                                                                                     │
│ ❱  653 │   │   return future.result()                                                            │
│    654 │                                                                                         │
│    655 │   def stop(self):                                                                       │
│    656 │   │   """Stop running the event loop.                                                   │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │   future = <Task finished name='Task-1' coro=<feed.<locals>.feed_() done, defined at         │ │
│ │            /root/e1radar/grpc/lib64/python3.11/site-packages/fr24/cli.py:91>                 │ │
│ │            exception=AssertionError()>                                                       │ │
│ │ new_task = False                                                                             │ │
│ │     self = <_UnixSelectorEventLoop running=False closed=True debug=False>                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /root/e1radar/grpc/lib64/python3.11/site-packages/fr24/cli.py:94 in feed_                        │
│                                                                                                  │
│    91 │   async def feed_() -> None:                                                             │
│    92 │   │   async with FR24() as fr24:                                                         │
│    93 │   │   │   lf = fr24.livefeed(timestamp)                                                  │
│ ❱  94 │   │   │   lf.data.add_api_response(await lf.api.fetch())                                 │
│    95 │   │   │   lf.data.save_parquet()                                                         │
│    96 │   │   │   rich.print(get_success_message(lf))                                            │
│    97                                                                                            │
│                                                                                                  │
│ ╭───────────────────────────── locals ─────────────────────────────╮                             │
│ │      fr24 = <fr24.core.FR24 object at 0x7fddb3228710>            │                             │
│ │        lf = <fr24.core.LiveFeedService object at 0x7fddb3228dd0> │                             │
│ │ timestamp = None                                                 │                             │
│ ╰──────────────────────────────────────────────────────────────────╯                             │
│                                                                                                  │
│ /root/e1radar/grpc/lib64/python3.11/site-packages/fr24/core.py:366 in fetch                      │
│                                                                                                  │
│   363 │   │   │   │   **kw,  # type: ignore[arg-type]                                            │
│   364 │   │   │   │   auth=self.http.auth,                                                       │
│   365 │   │   │   )                                                                              │
│ ❱ 366 │   │   resp = await livefeed_world_data(self.http.client, self.http.auth)                 │
│   367 │   │   self.ctx["timestamp"] = int(time.time())                                           │
│   368 │   │   return resp                                                                        │
│   369                                                                                            │
│                                                                                                  │
│ ╭──────────────────────── locals ─────────────────────────╮                                      │
│ │ self = <fr24.core.LiveFeedAPI object at 0x7fddb3228e50> │                                      │
│ │   ts = None                                             │                                      │
│ ╰─────────────────────────────────────────────────────────╯                                      │
│                                                                                                  │
│ /root/e1radar/grpc/lib64/python3.11/site-packages/fr24/livefeed.py:224 in livefeed_world_data    │
│                                                                                                  │
│   221 │   client: httpx.AsyncClient, auth: None | Authentication = None                          │
│   222 ) -> list[LiveFeedRecord]:                                                                 │
│   223 │   """Retrieve live feed data for the entire world, in chunks."""                         │
│ ❱ 224 │   results = await asyncio.gather(                                                        │
│   225 │   │   *[                                                                                 │
│   226 │   │   │   livefeed_post(                                                                 │
│   227 │   │   │   │   client,                                                                    │
│                                                                                                  │
│ ╭─────────────────────── locals ────────────────────────╮                                        │
│ │   auth = None                                         │                                        │
│ │ client = <httpx.AsyncClient object at 0x7fddb3228850> │                                        │
│ ╰───────────────────────────────────────────────────────╯                                        │
│                                                                                                  │
│ /root/e1radar/grpc/lib64/python3.11/site-packages/fr24/livefeed.py:176 in livefeed_post          │
│                                                                                                  │
│   173 │   """Send the request and extract the raw protobuf message."""                           │
│   174 │   response = await client.send(request)                                                  │
│   175 │   data = response.content                                                                │
│ ❱ 176 │   assert len(data) and data[0] == 0                                                      │
│   177 │   data_len = int.from_bytes(data[1:5], byteorder="big")                                  │
│   178 │   return data[5 : 5 + data_len]                                                          │
│   179                                                                                            │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │   client = <httpx.AsyncClient object at 0x7fddb3228850>                                      │ │
│ │     data = b''                                                                               │ │
│ │  request = <Request('POST',                                                                  │ │
│ │            'https://data-feed.flightradar24.com/fr24.feed.api.v1.Feed/LiveFeed')>            │ │
│ │ response = <Response [464 ]>                                                                 │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯

**Comment by tuannguyen1999xxx** [comment]
livefeed return empty data too

**Comment by sejo21** [comment]
yes, the main CLI and the whole world feed uses the livefeed component I think which is what is broken.  I think maybe FR24 have changed the protocol so it needs updating.  Hopefully the author can fix it soon because this is a great library.

**Comment by cathaypacific8747** [comment]
I am unable to reproduce the empty response on my end: the manually triggered test [here](https://github.com/cathaypacific8747/fr24/actions/runs/9197051007/job/25296589588) also indicate all passes.

I had a quick check and there seems to be no protocol changes.

In my experience, empty responses usually occurs when you are being ratelimited. Are you authenticated with your subscription key and/or username+password?

**Comment by cathaypacific8747** [comment]
@sejo21 Upon closer inspection, the response code was 464, indicating that there was a mismatch in HTTP protocol. HTTPX uses HTTP/1.1 by default: can you modify this line to `httpx.AsyncClient(http2=True)`

https://github.com/cathaypacific8747/fr24/blob/755ccf2dd2676e28f916120f21aec858c20dafac/tests/test_misc.py#L23

and check that `pytest tests/test_misc.py::test_simple` passes? If so, I think we should move towards enabling HTTP/2 by default.

**Comment by cathaypacific8747** [comment]
Great to know it is resolved. It is likely an issue on fr24's side as I have also been encountering intermittent (though very temporary) connection errors. 

I'm currently working on a [new core](https://github.com/cathaypacific8747/fr24/pull/24) and will be enabling HTTP/2 by default. The workaround for now is to pass in a custom AsyncClient to the [`FR24`](https://cathaypacific8747.github.io/fr24/api/core/#fr24.core.FR24) constructor:
```py
from fr24.core import FR24
import httpx

async def my_feed():
    client = httpx.AsyncClient(http2=True)  # adding transport=httpx.AsyncHTTPTransport(retries=5) also helps
    async with FR24(client) as fr24:
        ...
```

**Comment by sejo21** [comment]
Thanks.  I just tried to add the line into my code but i get an error when i try it.  Its bound to be me doing it wrong -  i dont fully understand all the async stuff as yet.  Here is a simplified bit of working code for me.

```
from fr24.core import FR24
import asyncio
import httpx

async def my_feed() -> None:
    async with FR24() as fr24:
        lf = fr24.livefeed()
        response = await lf.api.fetch()
        print(response)
        lf.data.add_api_response(response)
        print(lf.data.df)
        lf.data.save_parquet()
        print(lf.data.fp)

a=asyncio.run(my_feed())
```

If I add the suggested lines for http2 into it i get errors

Any ideas what I'm doing wrong?

```
from fr24.core import FR24
import asyncio
import httpx

async def my_feed() -> None:
    client = httpx.AsyncClient(http2=True)
    async with FR24(client) as fr24:
        lf = fr24.livefeed()
        response = await lf.api.fetch()
        print(response)
        lf.data.add_api_response(response)
        print(lf.data.df)
        lf.data.save_parquet()
        print(lf.data.fp)

a=asyncio.run(my_feed())
```

> (grpc) [root@smj-centos-6 grpc]# python w2.py
> Traceback (most recent call last):
>   File "/root/e1radar/grpc/w2.py", line 16, in <module>
>     a=asyncio.run(my_feed())
>       ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib64/python3.11/asyncio/runners.py", line 190, in run
>     return runner.run(main)
>            ^^^^^^^^^^^^^^^^
>   File "/usr/lib64/python3.11/asyncio/runners.py", line 118, in run
>     return self._loop.run_until_complete(task)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib64/python3.11/asyncio/base_events.py", line 653, in run_until_complete
>     return future.result()
>            ^^^^^^^^^^^^^^^
>   File "/root/e1radar/grpc/w2.py", line 8, in my_feed
>     lf = fr24.livefeed()
>          ^^^^^^^^^^^^^^^
>   File "/root/e1radar/grpc/lib64/python3.11/site-packages/fr24/core.py", line 117, in livefeed
>     return LiveFeedService(
>            ^^^^^^^^^^^^^^^^
>   File "/root/e1radar/grpc/lib64/python3.11/site-packages/fr24/core.py", line 414, in __init__
>     fs = LiveFeedArrow(base_dir, ctx)
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/root/e1radar/grpc/lib64/python3.11/site-packages/fr24/base.py", line 62, in __init__
>     self.base_dir = Path(base_dir)
>                     ^^^^^^^^^^^^^^
>   File "/usr/lib64/python3.11/pathlib.py", line 871, in __new__
>     self = cls._from_parts(args)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib64/python3.11/pathlib.py", line 509, in _from_parts
>     drv, root, parts = self._parse_args(args)
>                        ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib64/python3.11/pathlib.py", line 493, in _parse_args
>     a = os.fspath(a)
>         ^^^^^^^^^^^^
> TypeError: expected str, bytes or os.PathLike object, not AsyncClient

**Comment by cathaypacific8747** [comment]
The one on Linux seems to be installed via pip, which does not accept custom `AsyncClient`s. Try reinstalling with
```
pip3 install git+https://github.com/cathaypacific8747/fr24.git
```
to grab the latest version

**Comment by sejo21** [comment]
Ah, OK.  Yes that's fixed it.  Just created a new venv and used the git version.

Thanks again.
