### ISSUE TITLE
How to pull back squawk code from live feed

### ISSUE THREAD

**Issue by sejo21** [cathaypacific8747/fr24#30]
Assuming I am using the example world feed code and I am authenticated...

```
from fr24.core import FR24

async def my_feed() -> None:
    async with FR24() as fr24:
        lf = fr24.livefeed()
        response = await lf.api.fetch()
        print(response)
        lf.data.add_api_response(response)
        print(lf.data.df)
        lf.data.save_parquet()
        print(lf.data.fp)

await my_feed()
```

I can see that there is reference in one of the lower level functions ( livefeed_message_create) to return optional extra fields if I am authenticated

>  When authenticated, squawk, vspeed, airspace, logo_id and age can be included

Is there a way to do this from the higher level core calls?  I want to pull back the squawk code for all aircraft in the livefeed.

Thanks ( I am sure there is - I'm just not sure how i would do it from the top level)

**Comment by cathaypacific8747** [comment]
It is not possible to specify the fields in the `FR24` core, but we are currently in the process of migrating to a new core (#24), which will allow you to do so. You could workaround this for now by calling the lower level functions or patching the library via editable mode.

**Comment by sejo21** [comment]
OK thanks.  Will look out for the new version, and have a go at "patching" a local copy in the meantime then.

**Comment by cathaypacific8747** [comment]
Just added the ability to specify fields in the new core:
```
git clone https://github.com/cathaypacific8747/fr24.git --depth 1
cd fr24
git fetch --depth=1 origin 8965fe2e186341d60b6fb0a2f9d3426610907eb4
git checkout 8965fe2e186341d60b6fb0a2f9d3426610907eb4
pip install .
```
Example:
```py
from fr24.core import FR24

async def my_feed() -> None:
    async with FR24() as fr24:
        await fr24.login()
        response = await fr24.livefeed.fetch(fields=["squawk", "route", "type"])
        datac = response.to_arrow()
        print(datac.df)
        datac.save()

await my_feed()
```
The new core will be finalised in the next few days and pushed to a pip.

**Comment by sejo21** [comment]
Amazing, thanks.  Will give that a try

**Comment by sejo21** [comment]
Hmm....so in the old version the output from the basic world feed example was a list of dictionaries that I could iterate over.

Now the output is more complicated as a pyarrow object?  

So is there an easy way to convert back to the old list format?

**Comment by sejo21** [comment]
OOps.  I figured it 

response.data

Thanks!

**Comment by sejo21** [comment]
Getting some odd values for the squawk codes.  Should only be a 4 digits - or do i need to convert it from an int?

**Comment by sejo21** [comment]
ok got it, convert to hex
