### ISSUE TITLE
Encrypted?

### ISSUE THREAD

**Issue by Flightliner380** [cathaypacific8747/fr24#50]
The latest Web / Mobile Apps looks like now the content is encrypted, currently the projekt still working.
Please can you check if it's possible to add the encrpytion?

**Comment by cathaypacific8747** [comment]
Content is not encrypted, but encoded in a binary format ([gRPC+protobuf](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md)). This library supports both the legacy JSON API and the new gRPC endpoint.

Documentation and usage examples could be found [here](https://cathaypacific8747.github.io/fr24/usage/examples/).
